### ISSUE TITLE
Server Crash on Pickaxe enchant Tunnel and Veinminer

### ISSUE THREAD

**Issue by skyman478** [nulli0n/ExcellentEnchants#19]
This error occours when a player im my server break a block and his pick has Tunnel and Veinminer, it is a loooong crash log and eventually the server stops

[06:07:44] [Server thread/ERROR]: Could not pass event BlockBreakEvent to ExcellentEnchants v3.0.6.4
java.lang.StackOverflowError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:171) ~[patched_1.17.1.jar:git-Paper-255]
	at org.apache.logging.log4j.core.impl.ThrowableProxyHelper.loadClass(ThrowableProxyHelper.java:216) ~[patched_1.17.1.jar:git-Paper-255]
	at org.apache.logging.log4j.core.impl.ThrowableProxyHelper.toExtendedStackTrace(ThrowableProxyHelper.java:114) ~[patched_1.17.1.jar:git-Paper-255]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:110) ~[patched_1.17.1.jar:git-Paper-255]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:94) ~[patched_1.17.1.jar:git-Paper-255]
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:347) ~[patched_1.17.1.jar:git-Paper-255]
	at org.apache.logging.log4j.core.impl.Log4jLogEvent$LogEventProxy.<init>(Log4jLogEvent.java:970) ~[patched_1.17.1.jar:git-Paper-255]
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:745) ~[patched_1.17.1.jar:git-Paper-255]

**Comment by nulli0n** [comment]
These enchantments are incompatible.

**Comment by skyman478** [comment]
if so, why they can be put together?. It was done using no command

**Comment by nulli0n** [comment]
Fixed
