### ISSUE TITLE
Doesn't work on Java 1.8 and 1.16.5

### ISSUE THREAD

**Issue by Bloodlex** [nulli0n/ExcellentEnchants#2]
[16:03:32] [Server thread/ERROR]: Could not load 'plugins/NexEngine.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: su/nexmedia/engine/NexEngine has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:263) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1070) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1060]

Sadly, I can't use it on my server anymore, since it's using 1.8 Java and 1.16.5. Is it possible to make it work? :(

**Comment by nulli0n** [comment]
Then use Java 16

**Comment by Bloodlex** [comment]
Okay, already changed, thanks
